"""
Vvault License Validator
Place this file in: app/services/license_service.py

Called on Vvault startup.
Reads .vvault-license from the Vvault folder.
Validates cryptographic signature using embedded public key.
Zero network calls. Fully offline. Air-gapped.
"""

import json
import base64
import os
import glob
from datetime import datetime
from typing import Optional
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding
from cryptography.hazmat.backends import default_backend
from cryptography.exceptions import InvalidSignature

# ── EMBED YOUR PUBLIC KEY HERE ──
# Replace this with the content of your public_key.pem
# (generated by generate_keys.py)
# Keep the exact formatting including newlines.

PUBLIC_KEY_PEM = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArkPNeMKhtAfjNbS1s1vS
89+ZKVvRuSb+t7S6w0WcJVK+1JOW6tsUpp5bItp+t0W/a6/hJDFmcycYYdGtibx6
E7nt7Cw3D8ZqiHgqurrjqFMREFbd6ckDFnFd/edAhCqPKdqCWZ09tI4iNEsdehyk
+k1wHG7fjjgQ54yaojjf6M2mjEmNh2hBvMEJ6+LRjeyKf7gqKhq6HW3YUNabnCi3
ArVGj7OeqIqsxdwrwg7ZgkQ/hObghdRxg5GzOAX6bG6ZXQInEVzHkD/Aiob0tRcr
BjsLhZjmw10chbg3YKU/3Q6Pd9r0XgEYi/K9xaD39Lqz4HM+8UZZ2qnqMhhr6ziR
XQIDAQAB
-----END PUBLIC KEY-----"""

# ── LICENSE STATUS ──
_license_status = {
    "valid":       False,
    "reason":      "not_checked",
    "email":       "",
    "company":     "",
    "plan":        "",
    "expires_at":  "",
    "days_remaining": 0,
    "max_users":   1,
    "checked_at":  ""
}


def load_public_key():
    """Load the embedded public key."""
    return serialization.load_pem_public_key(
        PUBLIC_KEY_PEM.strip().encode('utf-8'),
        backend=default_backend()
    )


def find_license_file() -> Optional[str]:
    """
    Search for .vvault-license file in common locations.
    Checks: /app, /app/license, current directory, home directory.
    """
    search_paths = [
        "/app/*.vvault-license",
        "/app/license/*.vvault-license",
        "*.vvault-license",
        os.path.expanduser("~/vvault/*.vvault-license"),
        os.path.expanduser("~/*.vvault-license"),
    ]
    
    for pattern in search_paths:
        matches = glob.glob(pattern)
        if matches:
            return matches[0]
    
    return None


def parse_license_file(filepath: str) -> Optional[dict]:
    """Extract JSON payload from the license file."""
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()

        begin_marker = '-----BEGIN VVAULT LICENSE-----'
        end_marker = '-----END VVAULT LICENSE-----'

        start = content.find(begin_marker)
        end = content.find(end_marker)

        if start == -1 or end == -1:
            return None

        between = content[start + len(begin_marker):end].strip()

        json_start = between.find('{')
        json_end = between.rfind('}') + 1

        if json_start == -1 or json_end == 0:
            return None

        json_only = between[json_start:json_end]
        return json.loads(json_only)

    except Exception as e:
        print(f"License parse error: {e}")
        return None

def verify_signature(license_data: dict) -> Optional[dict]:
    """
    Verify the RSA signature on the license payload.
    Returns the decoded payload if valid, None if invalid.
    """
    try:
        payload_b64 = license_data.get("payload", "")
        signature_b64 = license_data.get("signature", "")
        
        if not payload_b64 or not signature_b64:
            return None
        
        payload_bytes = base64.b64decode(payload_b64)
        signature = base64.b64decode(signature_b64)
        
        public_key = load_public_key()
        
        # Verify signature
        public_key.verify(
            signature,
            payload_bytes,
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=padding.PSS.MAX_LENGTH
            ),
            hashes.SHA256()
        )
        
        # Signature valid — decode payload
        return json.loads(payload_bytes.decode('utf-8'))
    
    except InvalidSignature:
        return None
    except Exception:
        return None


def validate_license() -> dict:
    """
    Main validation function.
    Called on Vvault startup.
    Returns license status dict.
    """
    global _license_status
    
    _license_status["checked_at"] = datetime.utcnow().isoformat()
    
    # Step 1: Find license file
    license_path = find_license_file()
    
    if not license_path:
        _license_status.update({
            "valid":  False,
            "reason": "no_license_file",
        })
        return _license_status
    
    # Step 2: Parse license file
    license_data = parse_license_file(license_path)
    
    if not license_data:
        _license_status.update({
            "valid":  False,
            "reason": "invalid_license_format",
        })
        return _license_status
    
    # Step 3: Verify cryptographic signature
    payload = verify_signature(license_data)
    
    if not payload:
        _license_status.update({
            "valid":  False,
            "reason": "invalid_signature",
        })
        return _license_status
    
    # Step 4: Check product
    if payload.get("product") != "vvault":
        _license_status.update({
            "valid":  False,
            "reason": "wrong_product",
        })
        return _license_status
    
    # Step 5: Check expiry
    try:
        expires = datetime.strptime(payload["expires_at"], "%Y-%m-%d")
        now = datetime.utcnow()
        days_remaining = (expires - now).days
        
        if now > expires:
            _license_status.update({
                "valid":        False,
                "reason":       "expired",
                "email":        payload.get("email", ""),
                "company":      payload.get("company", ""),
                "expires_at":   payload["expires_at"],
                "days_remaining": 0
            })
            return _license_status
    
    except Exception:
        _license_status.update({
            "valid":  False,
            "reason": "invalid_expiry_date",
        })
        return _license_status
    
    # All checks passed
    _license_status.update({
        "valid":          True,
        "reason":         "ok",
        "email":          payload.get("email", ""),
        "company":        payload.get("company", ""),
        "plan":           payload.get("plan", "annual"),
        "expires_at":     payload["expires_at"],
        "days_remaining": days_remaining,
        "max_users":      payload.get("max_users", 999),
        "license_path":   license_path
    })
    
    # Warning if expiring soon
    if days_remaining <= 30:
        _license_status["reason"] = "expiring_soon"
    
    return _license_status


def get_license_status() -> dict:
    """Get cached license status."""
    return _license_status


def is_valid() -> bool:
    """Quick check — is the license valid?"""
    return _license_status.get("valid", False)


def get_expiry_message() -> Optional[str]:
    """
    Returns a user-facing message if action needed.
    None if everything is fine.
    """
    status = _license_status
    
    if not status["valid"]:
        reason = status.get("reason", "unknown")
        
        if reason == "no_license_file":
            return (
                "No license file found. "
                "Please place your .vvault-license file in the Vvault folder "
                "and restart. Contact support@getvvault.com if you need help."
            )
        elif reason == "expired":
            return (
                f"Your Vvault license expired on {status.get('expires_at', 'unknown')}. "
                f"Please renew at getvvault.com to continue using Vvault."
            )
        elif reason == "invalid_signature":
            return (
                "Your license file appears to be modified or corrupted. "
                "Please contact support@getvvault.com for a replacement."
            )
        else:
            return (
                f"License validation failed ({reason}). "
                "Please contact support@getvvault.com."
            )
    
    if status.get("reason") == "expiring_soon":
        days = status.get("days_remaining", 0)
        return (
            f"Your Vvault license expires in {days} days. "
            f"Please renew at getvvault.com to avoid interruption."
        )
    
    return None
