
services:

  db:
    image: ankane/pgvector
    container_name: vvault_db
    environment:
      POSTGRES_DB: vvault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    container_name: vvault_backend
    depends_on:
      - db
    env_file:
      - .env  
    environment:
      DB_HOST: db
      DB_NAME: vvault
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
       - .:/app  
       - ./vvault-vvault-internal-2027.vvault-license:/app/vvault-vvault-internal-2027.vvault-license

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
      - "3443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend

 

  ollama:
    image: ollama/ollama
    container_name: vvault_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama    
    entrypoint: >
      sh -c "
      ollama serve &
      sleep 5 &&
      ollama pull phi3:mini &&
      ollama pull nomic-embed-text &&
      wait
      "

volumes:
  pgdata:
  ollama_data: