"""
Generate a 300-question SOC2/security test questionnaire Excel file.
Output: test_data/soc2_300_questions.xlsx
"""

import os
import openpyxl

OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "test_data", "soc2_300_questions.xlsx")

QUESTIONS = {
    "Access Control": [
        "Do you enforce multi-factor authentication (MFA) for all user accounts?",
        "How are privileged accounts managed and monitored?",
        "Is there a formal process for granting and revoking user access?",
        "How frequently are user access rights reviewed?",
        "Do you enforce the principle of least privilege?",
        "Are shared accounts prohibited across your systems?",
        "How are terminated employees' access rights revoked?",
        "Do you maintain an inventory of all user accounts with privileged access?",
        "Is access to production systems restricted to authorized personnel only?",
        "How is remote access to internal systems secured?",
        "Do you use role-based access control (RBAC)?",
        "Are service accounts audited and rotated regularly?",
        "How are contractors and third-party users granted system access?",
        "Is SSH key-based authentication enforced for server access?",
        "Do you enforce password complexity and rotation policies?",
        "Are admin accounts separate from standard user accounts?",
        "Do you log all privileged access and activities?",
        "Is there a process to detect and disable dormant accounts?",
        "How is access to source code repositories controlled?",
        "Do you enforce session timeouts for inactive users?",
        "Is access to customer data restricted on a need-to-know basis?",
        "How do you manage API keys and service credentials?",
        "Are database access permissions reviewed quarterly?",
        "Do you use single sign-on (SSO) across your applications?",
        "Is there a formal access request and approval workflow?",
        "How are password resets handled securely?",
        "Do you enforce device-based access controls (MDM)?",
        "Are privileged access workstations (PAWs) used for admin tasks?",
        "How is access to cloud management consoles controlled?",
        "Do you monitor for unauthorized access attempts in real time?",
        "Is there a process for emergency access (break-glass) procedures?",
        "Are federated identity providers used for authentication?",
        "How are OAuth tokens and sessions managed and expired?",
        "Do you enforce IP allowlisting for sensitive admin portals?",
        "Is there a recertification process for access rights annually?",
        "How is access to backup systems controlled?",
        "Are there controls preventing bulk data exports by regular users?",
        "Do you separate dev, staging, and production access?",
        "Is there an audit trail for all access provisioning changes?",
        "How do you handle access for mergers or acquisitions?",
    ],

    "Encryption and Data Protection": [
        "Is data encrypted at rest using industry-standard algorithms (AES-256)?",
        "Is data encrypted in transit using TLS 1.2 or higher?",
        "How are encryption keys managed and rotated?",
        "Do you use a dedicated key management service (KMS)?",
        "Is customer data encrypted at the field or column level where required?",
        "Are database backups encrypted?",
        "How is encryption enforced on employee laptops and mobile devices?",
        "Do you perform regular audits of your encryption posture?",
        "Are cryptographic libraries kept up to date?",
        "Do you prohibit the use of weak or deprecated ciphers (e.g. MD5, SHA-1)?",
        "Is data classified by sensitivity, and are controls applied per classification?",
        "How is personally identifiable information (PII) protected?",
        "Do you implement data masking in non-production environments?",
        "Are secrets and credentials stored in a vault (e.g. HashiCorp Vault, AWS Secrets Manager)?",
        "Is there a data retention and disposal policy?",
        "How is data securely deleted when no longer needed?",
        "Do you encrypt inter-service communication within your infrastructure?",
        "Is there a process to detect unencrypted sensitive data in storage?",
        "How are TLS certificates managed and rotated?",
        "Are certificate expiry alerts in place to avoid outages?",
        "Do you enforce HTTPS across all customer-facing endpoints?",
        "Is there a process for handling data subject to export regulations (ITAR, EAR)?",
        "How is data protected in transit between cloud regions?",
        "Do you use hardware security modules (HSMs) for key storage?",
        "Is customer data logically isolated from other customers' data?",
        "Do you implement tokenization for payment card data?",
        "How are backup encryption keys managed separately from backups?",
        "Is there a process to test the recoverability of encrypted backups?",
        "Do you perform regular key rotation for all cryptographic material?",
        "Are there controls to detect and alert on use of deprecated protocols?",
        "Is end-to-end encryption used for sensitive communications?",
        "How is data anonymization verified to be irreversible?",
        "Do you maintain an inventory of all systems storing sensitive data?",
        "Are there controls preventing copying of sensitive data to personal storage?",
        "How is encryption validated during third-party audits?",
        "Is DLP (data loss prevention) tooling deployed?",
        "Are email communications with sensitive data encrypted?",
        "How is data sovereignty enforced for customers in specific regions?",
        "Is there a process to revoke access to encrypted data when keys are compromised?",
        "Are cryptographic algorithm choices reviewed annually for post-quantum readiness?",
    ],

    "Incident Response": [
        "Do you have a documented incident response plan (IRP)?",
        "How frequently is the incident response plan tested?",
        "Who is responsible for declaring a security incident?",
        "What is your target time to detect and contain a security breach?",
        "Do you have a dedicated security incident response team (SIRT)?",
        "How are customers notified in the event of a data breach?",
        "Is there a process to preserve evidence during incident investigation?",
        "How do you classify and prioritize security incidents by severity?",
        "Do you conduct post-incident reviews and publish findings internally?",
        "Are lessons learned from incidents incorporated into security controls?",
        "Do you maintain an incident log with timelines and resolution details?",
        "Is there a runbook for common incident types (ransomware, data leak, etc.)?",
        "How are third-party vendors notified when they are involved in an incident?",
        "Do you have a 24/7 on-call security team?",
        "How do you coordinate with law enforcement during major incidents?",
        "Is there a defined communication tree for escalating incidents?",
        "Are forensic tools available and pre-deployed for incident investigation?",
        "Do you use a SIEM for centralized log analysis during incidents?",
        "How are affected systems isolated without disrupting production?",
        "Is the incident response plan compliant with GDPR breach notification requirements?",
        "Do you conduct tabletop exercises for incident response at least annually?",
        "Are incident response procedures integrated with your CI/CD pipeline?",
        "How long do you retain incident-related logs and artifacts?",
        "Is there a bug bounty or responsible disclosure program in place?",
        "How are security vulnerabilities reported by internal staff handled?",
        "Do you have cyber insurance coverage for breach-related costs?",
        "Are incident response contacts kept up to date and accessible offline?",
        "How do you handle incidents involving cloud provider outages?",
        "Is there a process to update customers on incident progress?",
        "Do you track mean time to respond (MTTR) and mean time to detect (MTTD)?",
    ],

    "Vulnerability Management": [
        "Do you have a formal vulnerability management program?",
        "How frequently are internal and external vulnerability scans performed?",
        "What is your SLA for remediating critical vulnerabilities?",
        "Do you perform penetration testing, and how often?",
        "Are third-party penetration test reports available for review?",
        "How are CVEs tracked and prioritized across your environment?",
        "Do you use an asset inventory to ensure all systems are scanned?",
        "Is there a patch management process for operating systems and software?",
        "How are zero-day vulnerabilities handled?",
        "Do you perform vulnerability scanning on container images?",
        "Are your CI/CD pipelines integrated with SAST and DAST tooling?",
        "How are open source dependencies monitored for vulnerabilities (SCA)?",
        "Is there a defined process for emergency patching outside the normal cycle?",
        "How do you validate that patches have been successfully applied?",
        "Are vulnerability scan results reviewed by a security team?",
        "Do you have a risk acceptance process for vulnerabilities that cannot be patched immediately?",
        "How are vulnerabilities discovered during development handled before release?",
        "Is there a responsible disclosure policy for external researchers?",
        "Are web applications scanned for OWASP Top 10 vulnerabilities?",
        "How is the attack surface reduced (hardening, unused services disabled)?",
        "Do you perform red team exercises?",
        "Are vulnerability metrics reported to executive leadership?",
        "Is there a process to verify that fixes resolve the underlying vulnerability?",
        "How are cloud misconfigurations detected and remediated?",
        "Do you use threat intelligence feeds to prioritize vulnerabilities?",
        "Are production systems scanned without disrupting services?",
        "How do you handle vulnerability disclosures from cloud providers?",
        "Is there a process to track vulnerabilities through to closure?",
        "Do you benchmark your vulnerability posture against industry peers?",
        "Are vulnerability management metrics tied to team performance goals?",
    ],

    "Business Continuity and DR": [
        "Do you have a documented business continuity plan (BCP)?",
        "How frequently is the BCP tested and updated?",
        "What is your recovery time objective (RTO) for critical systems?",
        "What is your recovery point objective (RPO) for critical data?",
        "Have you performed a business impact analysis (BIA)?",
        "Are backups performed daily and stored off-site?",
        "How is backup integrity verified?",
        "Do you have a documented disaster recovery plan (DRP)?",
        "How frequently are DR failover tests conducted?",
        "Is there a secondary data center or cloud region for failover?",
        "Are critical systems deployed with high availability (HA) configurations?",
        "How are single points of failure identified and mitigated?",
        "Do you have redundant internet connectivity and network paths?",
        "Is there a process for maintaining operations during extended outages?",
        "How are employees notified and activated during a disaster scenario?",
        "Are key personnel contact details maintained and tested?",
        "Is the BCP reviewed after each major incident or organizational change?",
        "Do you have documented manual procedures for when systems are unavailable?",
        "How long are backups retained, and are multiple versions kept?",
        "Are backup restoration procedures documented and tested?",
        "Do you track and publish uptime SLAs to customers?",
        "Is there a process to prioritize recovery of systems by criticality?",
        "How are third-party dependencies accounted for in the DR plan?",
        "Are DR exercises conducted with full participation from operations teams?",
        "Do you maintain copies of critical documentation outside your primary systems?",
        "How is data residency maintained during a DR failover?",
        "Are chaos engineering practices used to validate resilience?",
        "Is there a communication plan for customers during DR events?",
        "How are licensing and compliance obligations met during failover?",
        "Do you have cyber resilience measures beyond traditional DR (e.g. immutable backups)?",
    ],

    "Vendor Management": [
        "Do you have a third-party vendor risk management policy?",
        "How are vendors assessed before being onboarded?",
        "Do you require vendors to complete security questionnaires?",
        "Are vendor contracts reviewed for security and data protection obligations?",
        "How frequently are critical vendors re-assessed?",
        "Do you maintain a register of all third-party vendors with data access?",
        "Are subprocessors identified and disclosed to customers?",
        "How is vendor compliance with data protection laws verified?",
        "Do you require vendors to notify you of security incidents?",
        "Is there a process to offboard vendors and revoke their access?",
        "Are data processing agreements (DPAs) in place with all relevant vendors?",
        "How do you assess the financial stability and continuity risk of critical vendors?",
        "Do you require SOC 2 Type II reports from key vendors?",
        "Are vendor access privileges reviewed and scoped to minimum necessary?",
        "Is there a process to monitor vendors for adverse events (news, breaches)?",
        "How are open source software dependencies treated as vendors?",
        "Do you conduct on-site audits of critical vendors?",
        "Are vendors required to maintain their own security certifications?",
        "How are vendor-supplied software components reviewed for vulnerabilities?",
        "Do you have a vendor concentration risk management process?",
        "How is customer data protected when shared with vendors?",
        "Are vendors required to delete data upon contract termination?",
        "Is there a process to manage vendor changes that could impact your security posture?",
        "Do you verify that vendors maintain adequate cyber insurance?",
        "How do you handle vendors operating in high-risk jurisdictions?",
    ],

    "Audit and Compliance": [
        "Are you SOC 2 Type II certified?",
        "Which compliance frameworks do you adhere to (ISO 27001, PCI DSS, HIPAA, etc.)?",
        "How frequently is an internal audit of security controls conducted?",
        "Are external audits performed annually?",
        "How are audit findings tracked and remediated?",
        "Is there a dedicated compliance function within the organization?",
        "How are regulatory changes monitored and incorporated into controls?",
        "Do you maintain a compliance calendar for all certification renewals?",
        "How are audit logs protected from tampering?",
        "Is there a process for employees to report compliance concerns anonymously?",
        "Are policies reviewed and approved by executive leadership annually?",
        "How is compliance training tracked and enforced for all employees?",
        "Do you maintain a risk register, and how is it updated?",
        "Is there a process for obtaining legal holds on data during litigation?",
        "How are control failures identified, escalated, and resolved?",
        "Do you perform continuous compliance monitoring using automated tooling?",
        "Are audit rights provided to enterprise customers in contracts?",
        "How is evidence collected and organized for external audits?",
        "Is there a whistleblower protection policy?",
        "Do you maintain a record of processing activities (ROPA) under GDPR?",
        "How is the scope of compliance certifications maintained as the product evolves?",
        "Are control owners assigned and accountable for each compliance domain?",
        "How do you demonstrate compliance to prospective customers during due diligence?",
        "Is there a process to manage exceptions to security policies?",
        "Do you participate in industry working groups or information sharing organizations (ISACs)?",
    ],

    "Network Security": [
        "Is your network segmented to separate production, staging, and development environments?",
        "Do you use firewalls to control inbound and outbound traffic?",
        "Is intrusion detection/prevention (IDS/IPS) deployed on your network?",
        "How is DNS security enforced (DNSSEC, DNS filtering)?",
        "Do you use a web application firewall (WAF)?",
        "How is DDoS protection implemented?",
        "Are network access control lists (ACLs) reviewed regularly?",
        "Is there a process for detecting and responding to unauthorized network devices?",
        "How is network traffic monitored and analyzed for anomalies?",
        "Do you use a zero-trust network architecture?",
        "Is VPN required for remote access to internal systems?",
        "How are network changes managed and reviewed?",
        "Are unused ports and services disabled on all network devices?",
        "Is there wireless network security (WPA3, guest network isolation)?",
        "How are network device configurations backed up and version-controlled?",
        "Do you perform regular network vulnerability assessments?",
        "Is east-west traffic between internal systems monitored?",
        "How is egress filtering implemented to prevent data exfiltration?",
        "Are BGP and routing protocols secured against hijacking?",
        "Do you use network flow analysis to detect lateral movement?",
        "Is there a process to detect rogue wireless access points?",
        "How are cloud VPCs and security groups configured and reviewed?",
        "Are network diagrams maintained and up to date?",
        "Is split tunneling disabled for VPN connections to production systems?",
        "Do you use microsegmentation within production environments?",
        "How is network access for IoT or operational technology (OT) devices controlled?",
        "Are there controls to prevent unauthorized VLAN hopping?",
        "How is SNMP secured or replaced with modern alternatives?",
        "Do you use private connectivity (VPN, Direct Connect) for cloud access?",
        "Are network security controls reviewed after significant infrastructure changes?",
    ],

    "Physical Security": [
        "Is access to your data center facilities badge-controlled?",
        "Are visitors to secure areas escorted and logged?",
        "How is physical access to server rooms monitored (CCTV, motion sensors)?",
        "Is there a process to revoke physical access badges for terminated employees?",
        "Are physical access logs reviewed regularly for anomalies?",
        "How are media containing sensitive data physically destroyed?",
        "Is there a clean desk policy to prevent information exposure?",
        "Are server racks and network equipment locked?",
        "How is physical security at colocation or cloud data centers verified?",
        "Is there environmental monitoring for temperature, humidity, and fire suppression?",
        "Are employees required to challenge unescorted individuals in secure areas?",
        "How are deliveries to secure areas screened and logged?",
        "Is there redundant power (UPS, generators) for critical systems?",
        "Are portable media devices (USB drives) prohibited in secure areas?",
        "How is physical security integrated with logical security monitoring?",
        "Are security cameras positioned to cover all entry and exit points?",
        "Is there a process to secure screen content in open-plan offices?",
        "Are laptops required to be secured with cable locks in public spaces?",
        "How is physical access reviewed after security incidents?",
        "Is there a process for reporting lost or stolen devices?",
    ],

    "Employee Security Training": [
        "Do all employees complete security awareness training upon onboarding?",
        "How frequently is mandatory security training refreshed for existing employees?",
        "Are phishing simulation exercises conducted for employees?",
        "How is employee compliance with security training tracked?",
        "Is there role-specific security training for engineering, finance, and HR teams?",
        "Are employees trained to identify and report social engineering attempts?",
        "How is training effectiveness measured and improved?",
        "Do executives and board members participate in security training?",
        "Is secure coding training mandatory for developers?",
        "Are employees trained on the company's incident reporting procedures?",
        "How are employees trained on handling sensitive customer data?",
        "Is there training specific to remote work security practices?",
        "Are employees required to acknowledge security policies annually?",
        "How are security training records maintained for audit purposes?",
        "Is there a process to update training content when new threats emerge?",
        "Are new phishing techniques incorporated into simulation exercises quarterly?",
        "Do employees receive training on data classification and handling?",
        "Is there a consequence framework for employees who fail security training?",
        "How are contractors and temporary staff included in security training programs?",
        "Are there dedicated security champions or liaisons within each team?",
        "Is there training for using company-approved tools and avoiding shadow IT?",
        "How is AI and LLM usage policy communicated and trained to employees?",
        "Are employees trained on travel security for high-risk geographies?",
        "Is there annual training on insider threat awareness?",
        "How are employees trained on acceptable use of company systems?",
        "Is there a security newsletter or internal communications program?",
        "Do employees receive briefings on recent industry breaches and lessons learned?",
        "Is there a security mentorship or buddy system for new hires?",
        "How are employees kept informed of changes to security policies?",
        "Is there a rewards program for employees who report security issues?",
    ],
}


def main():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "SOC2 Assessment"

    ws.append(["Question", "Answer"])

    total = 0
    for category, questions in QUESTIONS.items():
        for question in questions:
            ws.append([question, ""])
            total += 1

    os.makedirs(os.path.dirname(os.path.abspath(OUTPUT_PATH)), exist_ok=True)
    wb.save(OUTPUT_PATH)

    print(f"\nGenerated: {OUTPUT_PATH}")
    print(f"{'Category':<40} {'Count':>5}")
    print("-" * 47)
    for category, questions in QUESTIONS.items():
        print(f"{category:<40} {len(questions):>5}")
    print("-" * 47)
    print(f"{'TOTAL':<40} {total:>5}")


if __name__ == "__main__":
    main()
